version: "3.9"

services:

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  redis:
    image: redis
    command: ["redis-server", "--requirepass", "ma_bird_171210"]



  backend:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - mongo
      - redis
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/gru
      SPRING_DATA_REDIS_HOST: redis