spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/messenger
    username: marie_sok
    password: ma_bird_171210
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

