# =========================
# Server
# =========================
server.port=8081
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# =========================
# Database (PostgreSQL)
# =========================
spring.datasource.url=jdbc:postgresql://localhost:5432/messenger
spring.datasource.username=marie_sok
spring.datasource.password=ma_bird_171210
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# =========================
# Flyway
# =========================
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration

# =========================
# JWT
# =========================
jwt.secret=forest_river_sunset_ocean_birds_sky_palms_seaside_171210
jwt.expiration-ms=86400000  # 1 ????

# =========================
# WebSocket
# =========================
spring.websocket.path=/ws
spring.websocket.sockjs.enabled=true

# =========================
# CORS
# =========================
spring.web.cors.allowed-origins=*
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS

# =========================
# Logging
# =========================
logging.level.org.springframework=INFO
logging.level.functional.unique.creator.kerry=DEBUG