version: '3.8'

services:
  mongo:
    image: mongo:7.0
    container_name: messenger
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: gru
      MONGO_INITDB_ROOT_PASSWORD: ma_bird_171210
      MONGO_INITDB_DATABASE: messenger
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: messenger_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  backend:
    build: .
    container_name: messenger_backend
    restart: unless-stopped
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://gru_db_user:ma_bird_171210@mongo:27017/messenger
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      JWT_SECRET: forest_river_sunset_ocean_birds_sky_palms_seaside_171210
      JWT_EXPIRATION: 86400000
    ports:
      - "8081:8081"
    depends_on:
      - mongo
      - redis

volumes:
  mongo_data: